#services:
#    jazzyweb_aulas_mentor_alimentos.example:
#        class: Jazzyweb\AulasMentor\AlimentosBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

parameters:
  jamab.model.class: Jazzyweb\AulasMentor\AlimentosBundle\Model\Model
  jamab.infosender.class: Jazzyweb\AulasMentor\AlimentosBundle\Services\InfoSender
  jamab.wikiservice.class: Jazzyweb\AulasMentor\AlimentosBundle\Services\WikiService

services:
  jamab.model:
     class: '%jamab.model.class%'
     arguments:
      - '%database_name%'
      - '%database_user%'
      - '%database_password%'
      - '%database_host%'

  jamab.infosender:
    class: '%jamab.infosender.class%'
    arguments: [ '@jamab.model', '@mailer' ]

  jamab.wikiservice:
    class: '%jamab.wikiservice.class%'
    arguments: [ 'https://es.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&format=json&rvsection=0&titles=']