#services:
#    jazzyweb_aulas_mentor_alimentos.example:
#        class: Jazzyweb\AulasMentor\AlimentosBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

parameters:
  jamab.model.class: Jazzyweb\AulasMentor\AlimentosBundle\Model\Model

services:
  jamab.model:
     class: '%jamab.model.class%'
     arguments:
      - '%database_name%'
      - '%database_user%'
      - '%database_password%'
      - '%database_host%'